package burp;

import org.w3c.dom.Document;
import org.xml.sax.InputSource;
import org.xml.sax.SAXException;

import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.ParserConfigurationException;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;

abstract class XmlImporterBase {

    Document loadFileIntoDocument(DocumentBuilder safeDocBuilder, File nmapXml) {
        try {
            FileInputStream fis = new FileInputStream(nmapXml);
            InputSource is = new InputSource(fis);
            return safeDocBuilder.parse(is);

        } catch (FileNotFoundException | SAXException e) {
        } catch (IOException e) {
            System.console().printf(e.getMessage());
        }

        return null;
    }

    DocumentBuilder createSafeDocumentFactory() {
        DocumentBuilderFactory docBuilderFactory = DocumentBuilderFactory.newInstance();

        // The xml generated by nmap includes a doctype, so we can't use the usual
        // XXE avoidance tactic "disallow-doctype-decl"
        // https://www.owasp.org/index.php/XML_External_Entity_(XXE)_Prevention_Cheat_Sheet#XMLReader
        try {
            docBuilderFactory.setFeature("http://xml.org/sax/features/external-general-entities", false);
            docBuilderFactory.setFeature("http://xml.org/sax/features/external-parameter-entities", false);
            docBuilderFactory.setFeature("http://apache.org/xml/features/nonvalidating/load-external-dtd", false);
            docBuilderFactory.setXIncludeAware(false);
            docBuilderFactory.setExpandEntityReferences(false);

            return docBuilderFactory.newDocumentBuilder();

        } catch (ParserConfigurationException e) {
            return null;
        }
    }
}
